import type { ApiIR } from "../ir/api.ts";
import type { ServiceIR, ServiceMethodIR, HttpServiceMethodIR } from "../ir/service.ts";
import { isHttpMethod } from "../ir/service.ts";
import type { TypeIR } from "../ir/types.ts";
import type { Generator, GeneratorContext, GeneratedFiles } from "./generator.ts";
import {
  tsClientGenerator,
  methodNames,
  declaredTypes,
  operationTypeNames,
  type TsClientOptions,
} from "./tsClient.ts";
import { docComment, typeIdentifiers } from "./tsTypes.ts";

export interface ReactQueryOptions extends TsClientOptions {}

interface QueryOp {
  name: string;
  capitalName: string;
  pathTemplate: string;
  hasSlots: boolean;
  hasRequiredSlots: boolean;
  optionsTypeName: string;
  resultTypeName: string;
  doc?: string;
}

interface MutationOp {
  name: string;
  capitalName: string;
  pathTemplate: string;
  method: string;
  hasSlots: boolean;
  optionsTypeName: string;
  resultTypeName: string;
  doc?: string;
}

function methodDoc(method: ServiceMethodIR): string {
  const isHttp = isHttpMethod(method);
  const summary = isHttp ? method.summary : undefined;
  const description = isHttp ? method.description : undefined;
  const deprecated = isHttp && method.deprecated ? { isDeprecated: true } : undefined;
  return docComment(
    {
      description: [summary, description]
        .filter((line): line is string => Boolean(line))
        .join("\n\n") || undefined,
      deprecated,
    },
    ""
  );
}

function emitReactQueryFiles(
  service: ServiceIR,
  types: Map<string, TypeIR> | undefined,
  context: GeneratorContext<ReactQueryOptions>
): GeneratedFiles {
  const names = methodNames(service);
  // Recomputed from the same service and types `tsClient` emits `api.ts` from,
  // so the alias names agree with that file by construction.
  const identifiers = typeIdentifiers(declaredTypes(service, types).keys());
  const aliasNames = operationTypeNames([...names.values()], identifiers);
  const queryOps: QueryOp[] = [];
  const mutationOps: MutationOp[] = [];

  for (const method of service.methods) {
    const name = names.get(method)!;
    const capitalName = name.charAt(0).toUpperCase() + name.slice(1);
    const aliases = aliasNames.get(name)!;
    const doc = methodDoc(method);

    const isHttp = isHttpMethod(method);
    const httpMethod = isHttp ? method.address.method.toUpperCase() : "POST";
    const pathTemplate = isHttp
      ? method.address.path
      : "service" in method.address && method.address.service && "method" in method.address && method.address.method
        ? `${method.address.service}/${method.address.method}`
        : "call";

    const isQuery = isHttp && ["GET", "HEAD", "OPTIONS"].includes(httpMethod);

    let hasSlots = false;
    let hasRequiredSlots = false;

    if (isHttp) {
      const http = method as HttpServiceMethodIR;
      const params = http.request.parameters ?? [];
      const hasBody = Boolean(http.request.body && http.request.body.length > 0);
      hasSlots = params.length > 0 || hasBody;

      const hasPath = params.some((p) => p.in === "path");
      const hasReqParam = params.some((p) => p.required);
      const hasReqBody = hasBody && http.request.bodyRequired !== false;

      hasRequiredSlots = hasPath || hasReqParam || hasReqBody;
    } else {
      hasSlots = true;
      hasRequiredSlots = true;
    }

    if (isQuery) {
      queryOps.push({
        name,
        capitalName,
        pathTemplate,
        hasSlots,
        hasRequiredSlots,
        optionsTypeName: aliases.options,
        resultTypeName: aliases.result,
        doc,
      });
    } else {
      mutationOps.push({
        name,
        capitalName,
        pathTemplate,
        method: httpMethod,
        hasSlots,
        optionsTypeName: aliases.options,
        resultTypeName: aliases.result,
        doc,
      });
    }
  }

  const banner = (what: string) =>
    `// Generated by wiz from ${service.name ?? "an OpenAPI document"}.\n` +
    `// ${what} Edit the document, not this file.\n`;

  // Exactly the alias names the file mentions, deduplicated and sorted, so the
  // emitted import stays clean under `noUnusedLocals`.
  const queryAliases = [
    ...new Set(queryOps.flatMap((op) => [op.optionsTypeName, op.resultTypeName])),
  ]
    .sort()
    .map((name) => `, type ${name}`)
    .join("");
  const mutationAliases = [
    ...new Set(mutationOps.flatMap((op) => [op.optionsTypeName, op.resultTypeName])),
  ]
    .sort()
    .map((name) => `, type ${name}`)
    .join("");

  const queryCode = [
    banner("React Query options getters and hooks for query operations."),
    'import { useQuery, type UseQueryOptions } from "@tanstack/react-query";',
    `import { defaultClient, type Client${queryAliases} } from "./api.ts";`,
    'import { createMutations } from "./mutations.ts";',
    "",
    ...queryOps.flatMap((op) => {
      const pathLit = JSON.stringify(op.pathTemplate);
      const optParamDecl = op.hasRequiredSlots
        ? `options: ${op.optionsTypeName}`
        : `options?: ${op.optionsTypeName}`;
      const callArgs = op.hasSlots
        ? `options as any, { signal }`
        : `{ ...options, signal } as any`;

      const optionsFnDoc = op.doc
        ? op.doc
        : `/** Query options getter for \`${op.name}\`. */\n`;
      const hookDoc = `/** React Query hook for \`${op.name}\`. */\n`;

      return [
        `${optionsFnDoc}export function get${op.capitalName}QueryOptions<`,
        `  TData = ${op.resultTypeName},`,
        "  TError = unknown",
        ">(",
        `  ${optParamDecl},`,
        `  queryOptions?: Omit<UseQueryOptions<${op.resultTypeName}, TError, TData>, "queryKey" | "queryFn">,`,
        "  client: Client = defaultClient()",
        ") {",
        "  return {",
        `    queryKey: [${pathLit}, options] as const,`,
        "    queryFn: ({ signal }: { signal?: AbortSignal }) =>",
        `      client.${op.name}(${callArgs}),`,
        "    ...queryOptions,",
        "  };",
        "}",
        "",
        `${hookDoc}export function use${op.capitalName}<`,
        `  TData = ${op.resultTypeName},`,
        "  TError = unknown",
        ">(",
        `  ${optParamDecl},`,
        `  queryOptions?: Omit<UseQueryOptions<${op.resultTypeName}, TError, TData>, "queryKey" | "queryFn">,`,
        "  client: Client = defaultClient()",
        ") {",
        `  return useQuery(get${op.capitalName}QueryOptions(options${op.hasRequiredSlots ? "" : "!"}, queryOptions, client));`,
        "}",
        "",
      ];
    }),
    "/** Factory binding all query options getters and query hooks to a custom client instance. */",
    "export function createQueries(client: Client = defaultClient()) {",
    "  return {",
    ...queryOps.map((op) => {
      const optParamDecl = op.hasRequiredSlots
        ? `options: ${op.optionsTypeName}`
        : `options?: ${op.optionsTypeName}`;
      return [
        `    get${op.capitalName}QueryOptions: <TData = ${op.resultTypeName}, TError = unknown>(`,
        `      ${optParamDecl},`,
        `      queryOptions?: Omit<UseQueryOptions<${op.resultTypeName}, TError, TData>, "queryKey" | "queryFn">`,
        `    ) => get${op.capitalName}QueryOptions<TData, TError>(options${op.hasRequiredSlots ? "" : "!"}, queryOptions, client),`,
        `    use${op.capitalName}: <TData = ${op.resultTypeName}, TError = unknown>(`,
        `      ${optParamDecl},`,
        `      queryOptions?: Omit<UseQueryOptions<${op.resultTypeName}, TError, TData>, "queryKey" | "queryFn">`,
        `    ) => use${op.capitalName}<TData, TError>(options${op.hasRequiredSlots ? "" : "!"}, queryOptions, client),`,
      ].join("\n");
    }),
    "  };",
    "}",
    "",
    "/** Factory binding all query and mutation hooks to a custom client instance. */",
    "export function createHooks(client: Client = defaultClient()) {",
    "  return {",
    "    ...createQueries(client),",
    "    ...createMutations(client),",
    "  };",
    "}",
    "",
  ].join("\n");

  const mutationCode = [
    banner("React Query options getters and hooks for mutation operations."),
    'import { useMutation, type UseMutationOptions } from "@tanstack/react-query";',
    `import { defaultClient, type Client${mutationAliases} } from "./api.ts";`,
    "",
    ...mutationOps.flatMap((op) => {
      const pathLit = JSON.stringify(op.pathTemplate);
      const methodLit = JSON.stringify(op.method);
      const optionsFnDoc = op.doc
        ? op.doc
        : `/** Mutation options getter for \`${op.name}\`. */\n`;
      const hookDoc = `/** React Query hook for \`${op.name}\`. */\n`;

      return [
        `${optionsFnDoc}export function get${op.capitalName}MutationOptions<`,
        "  TError = unknown",
        ">(",
        `  mutationOptions?: Omit<UseMutationOptions<${op.resultTypeName}, TError, ${op.optionsTypeName}>, "mutationFn">,`,
        "  client: Client = defaultClient()",
        ") {",
        "  return {",
        `    mutationKey: [${pathLit}, ${methodLit}] as const,`,
        `    mutationFn: (options: ${op.optionsTypeName}) =>`,
        `      client.${op.name}(options as any),`,
        "    ...mutationOptions,",
        "  };",
        "}",
        "",
        `${hookDoc}export function use${op.capitalName}<`,
        "  TError = unknown",
        ">(",
        `  mutationOptions?: Omit<UseMutationOptions<${op.resultTypeName}, TError, ${op.optionsTypeName}>, "mutationFn">,`,
        "  client: Client = defaultClient()",
        ") {",
        `  return useMutation(get${op.capitalName}MutationOptions<TError>(mutationOptions, client));`,
        "}",
        "",
      ];
    }),
    "/** Factory binding all mutation options getters and mutation hooks to a custom client instance. */",
    "export function createMutations(client: Client = defaultClient()) {",
    "  return {",
    ...mutationOps.map((op) => {
      return [
        `    get${op.capitalName}MutationOptions: <TError = unknown>(`,
        `      mutationOptions?: Omit<UseMutationOptions<${op.resultTypeName}, TError, ${op.optionsTypeName}>, "mutationFn">`,
        `    ) => get${op.capitalName}MutationOptions<TError>(mutationOptions, client),`,
        `    use${op.capitalName}: <TError = unknown>(`,
        `      mutationOptions?: Omit<UseMutationOptions<${op.resultTypeName}, TError, ${op.optionsTypeName}>, "mutationFn">`,
        `    ) => use${op.capitalName}<TError>(mutationOptions, client),`,
      ].join("\n");
    }),
    "  };",
    "}",
    "",
  ].join("\n");

  return {
    "queries.ts": queryCode,
    "mutations.ts": mutationCode,
  };
}

export const reactQueryGenerator: Generator<ReactQueryOptions> = {
  name: "react-query-client",

  api(ir: ApiIR, context) {
    const baseFiles = tsClientGenerator.api!(ir, context);
    const reactQueryFiles = emitReactQueryFiles(ir.service, ir.types, context);
    return { ...baseFiles, ...reactQueryFiles };
  },

  service(ir: ServiceIR, context) {
    const baseFiles = tsClientGenerator.service!(ir, context);
    const reactQueryFiles = emitReactQueryFiles(ir, undefined, context);
    return { ...baseFiles, ...reactQueryFiles };
  },

  type(ir: TypeIR, context) {
    return tsClientGenerator.type ? tsClientGenerator.type(ir, context) : {};
  },
};

export default reactQueryGenerator;
