import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import * as ts from "typescript";
import {
  localAlias,
  transformSource,
  type GeneratedModule,
} from "../plugin.ts";
import { VIRTUAL_ENTRY } from "../generators/virtualGenerator.ts";
import { type GeneratedFiles } from "../generators/generator.ts";
import { silentLogger, type WizLogger } from "../logger.ts";

/**
 * Writing the plugin's output to disk instead of handing it to Bun.
 *
 * Nothing is regenerated here: `transformSource` is the same function the
 * plugin runs, so ejected code behaves exactly as a built one would. Only the
 * destination differs - a real file rather than a module the bundler resolves.
 */

export interface EjectedFile {
  /** Path relative to the eject root, with forward slashes. */
  path: string;
  contents: string;
}

/**
 * A readable directory name for a generated module's mount.
 *
 * The type key is `<digest>_<sanitised declaring path>_<TypeName>`, which is a
 * good cache key and a terrible directory name - it embeds the absolute path of
 * whoever ran the build. The digest already carries the uniqueness, so the name
 * only needs to be legible; a collision falls back to the full key.
 */
function shortModuleName(hash: string, taken: Map<string, string>): string {
  const existing = taken.get(hash);
  if (existing) return existing;

  const parts = hash.split("_").filter(Boolean);
  const digest = parts[0] ?? hash;
  const typeName = parts.length > 1 ? parts[parts.length - 1]! : "type";
  const candidate = `wiz-${typeName}-${digest}`;

  const claimed = new Set(taken.values());
  const name = claimed.has(candidate) ? `wiz-virtual-${hash}` : candidate;
  taken.set(hash, name);
  return name;
}

/**
 * Ejected code is output, not input.
 *
 * Its helpers are already resolved, and it declares functions called `validate`
 * and `is`, which is exactly what the plugin looks for when deciding whether a
 * file is worth transforming. Without this marker, building an ejected tree
 * would put it through the transform a second time.
 */
const EJECTED_HEADER = [
  "// @wiz-ignore",
  "// Generated by `wiz eject`; the wiz helpers here are already resolved.",
].join("\n");

function marked(code: string): string {
  return `${EJECTED_HEADER}\n${code}`;
}


function basenameOf(path: string): string {
  return path.replace(/\\/g, "/").split("/").pop()!;
}

/**
 * Folds a generated module into the file that uses it.
 *
 * The module's own name is scoped away inside a function, because a file using
 * two types pulls in two modules and both define `validate`, `is` and the
 * rest. Only the names the code actually reads are bound outside.
 */
function inlineModule(module: GeneratedModule): string {
  const bindings = module.exports
    .map((name) => `  ${name}: ${localAlias(name, module.hash)},`)
    .join("\n");
  const returned = module.exports.join(", ");

  return [
    `// Generated by wiz for type key ${module.hash}.`,
    `const {`,
    bindings,
    `} = (() => {`,
    module.files[VIRTUAL_ENTRY]!
      .split("\n")
      .map((line) => `  ${line.replace(/^export /, "")}`)
      .join("\n"),
    `  return { ${returned} };`,
    `})();`,
  ].join("\n");
}

/**
 * Removes value imports from wiz that the rewrite made unnecessary.
 *
 * Ejected code should not depend on wiz, but type-only imports such as
 * `NumberedUnion` still have to typecheck, so a name is dropped only when it
 * appears nowhere else in the file. Keeping one that is unused is untidy;
 * dropping one that is used does not compile, so the bias is towards keeping.
 */
function dropDeadWizImports(code: string): string {
  const lines = code.split("\n");
  const kept: string[] = [];

  // Every import is excluded, not just the one under test: the generated import
  // reads `{ is as __wiz_is_… }`, whose bare `is` would look like a use.
  const body = lines.filter((line) => !/^import\b/.test(line)).join("\n");

  for (const line of lines) {
    const match = /^import\s+(type\s+)?\{([^}]*)\}\s+from\s+"([^"]*wiz[^"]*)";?\s*$/.exec(line);
    if (!match) {
      kept.push(line);
      continue;
    }

    const names = match[2]!.split(",").map((n) => n.trim()).filter(Boolean);
    const used = names.filter((entry) => {
      const local = entry.split(/\s+as\s+/).pop()!.trim();
      return new RegExp(`\\b${local}\\b`).test(body);
    });

    if (used.length === names.length) kept.push(line);
    else if (used.length > 0) {
      kept.push(`import ${match[1] ?? ""}{ ${used.join(", ")} } from "${match[3]}";`);
    }
    // else: every name went, so the declaration goes with them.
  }

  return kept.join("\n");
}

/** After the leading run of imports, so the file still reads top-down. */
function spliceAfterImports(code: string, block: string): string {
  const lines = code.split("\n");
  let at = 0;
  for (let i = 0; i < lines.length; i++) {
    if (/^import\b/.test(lines[i]!)) at = i + 1;
    else if (lines[i]!.trim() !== "" && at > 0) break;
  }
  return [...lines.slice(0, at), "", block, ...lines.slice(at)].join("\n");
}

/**
 * Ejects one file into one self-contained file.
 *
 * Anything that would need to read another module is refused rather than
 * answered partially; that is what the project form is for.
 */
export function ejectFile(
  path: string,
  contents: string,
  logger: WizLogger = silentLogger
): string {
  const result = transformSource({
    path,
    contents,
    logger,
    isolated: true,
    inline: true,
  });

  const inlined = [...result.modules.values()]
    .filter((module) => module.exports.length > 0)
    .map(inlineModule);

  if (!result.changed) return result.code;

  const code = dropDeadWizImports(result.code);
  return marked(
    inlined.length > 0 ? spliceAfterImports(code, inlined.join("\n\n")) : code
  );
}

/**
 * Ejects every file a tsconfig includes.
 *
 * Generated modules stay separate here, as siblings of the file importing
 * them: a project shares types across files, and inlining would copy the same
 * generated code into each one.
 */
export function ejectProject(
  projectDir: string,
  logger: WizLogger = silentLogger
): EjectedFile[] {
  const configPath = join(projectDir, "tsconfig.json");
  if (!ts.sys.fileExists(configPath)) {
    throw new Error(
      `no tsconfig.json in ${projectDir}; a project eject needs one to know which files to read`
    );
  }

  const read = ts.readConfigFile(configPath, ts.sys.readFile);
  if (read.error) {
    throw new Error(
      `could not read ${configPath}: ${ts.flattenDiagnosticMessageText(read.error.messageText, " ")}`
    );
  }

  const parsed = ts.parseJsonConfigFileContent(read.config ?? {}, ts.sys, projectDir);

  const files: EjectedFile[] = [];
  const written = new Set<string>();
  const shortNames = new Map<string, string>();

  for (const fileName of parsed.fileNames) {
    if (fileName.includes("node_modules")) continue;
    if (fileName.endsWith(".d.ts")) continue;

    const contents = ts.sys.readFile(fileName);
    if (contents === undefined) continue;

    const result = transformSource({ path: fileName, contents, logger });
    const relativePath = relative(projectDir, fileName).replace(/\\/g, "/");
    const dir = dirname(relativePath);

    let code = result.code;
    const emitted: EjectedFile[] = [];

    for (const [root, module] of result.modules) {
      const short = shortModuleName(module.hash, shortNames);
      // The root is the directory the import starts with, so swapping it keeps
      // the file name inside - `./wiz-virtual/<key>/index.js` becomes
      // `./wiz-User-<digest>/index.js`, still relative, still named for the type.
      code = code.replaceAll(root, `./${short}`);

      const moduleDir = dir === "." ? short : `${dir}/${short}`;
      for (const [file, contents] of Object.entries(module.files)) {
        // One generated module is often imported from several files.
        const target = `${moduleDir}/${file}`;
        if (written.has(target)) continue;
        written.add(target);
        emitted.push({ path: target, contents: marked(contents) });
      }
    }
    void VIRTUAL_ENTRY;

    // Untouched files are copied byte for byte, so the tree still runs; only
    // what wiz rewrote carries the marker.
    const ejected = result.changed
      ? marked(dropDeadWizImports(code))
      : result.code;
    files.push({ path: relativePath, contents: ejected });
    files.push(...emitted);
  }

  return files;
}

/** Writes an ejected tree, creating directories as needed. */
export async function writeEjected(
  outDir: string,
  files: EjectedFile[]
): Promise<void> {
  for (const file of files) {
    const target = isAbsolute(file.path) ? file.path : resolve(outDir, file.path);
    await Bun.write(target, file.contents);
  }
}

export { basenameOf };
